version: '3'
services:
  web:
    container_name: recycleit
    restart: always
    build: ./
    command: npm run develop
    volumes:
      - ./:/code
    ports:
      - "5000:5000"
    # command:
    #   - yarn
    #   - run
    #   - develop